"""Initial migration

Revision ID: 024decf2390c
Revises: 
Create Date: 2025-06-23 17:07:29.605001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '024decf2390c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genresTable',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('moviesTable',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_moviesTable_title'), 'moviesTable', ['title'], unique=False)
    op.create_table('usersTable',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interactionsTable',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('movie_id', sa.Uuid(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['moviesTable.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['usersTable.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'movie_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interactionsTable')
    op.drop_table('usersTable')
    op.drop_index(op.f('ix_moviesTable_title'), table_name='moviesTable')
    op.drop_table('moviesTable')
    op.drop_table('genresTable')
    # ### end Alembic commands ###
